### ISSUE TITLE
US 09.01.01 

### ISSUE THREAD

**Issue by jimyl1** [CMPUT301W23T12/6ixStacks#14]
As an owner, I don’t want to store big images online.

# Acceptance Criteria 
- Profile pictures are resized and compressed before storing them in the database

# Unknown 
- How to stop someone from posting a inappropriate picture

**Comment by AdibNasreddine** [comment]
Blocked by #9

**Comment by MohamedAl-Nassirat** [comment]
unblocked as #9 is completed

**Comment by aeldidi** [comment]
Done because there's no part of the app which needs to store images. QR code images and profile pictures are automatically generated on the fly.
