### ISSUE TITLE
Planning UI Mockups

### ISSUE THREAD

**Issue by aeldidi** [CMPUT301W23T12/6ixStacks#2]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements.

**Comment by AbdullahiNur2828** [comment]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements.

**Comment by MohamedAl-Nassirat** [comment]
Completed. https://github.com/CMPUT301W23T12/6ixStacks/wiki/UI-Mockups-and-Storyboard-Sequences:
