### ISSUE TITLE
Purchase new QR codes at Shop

### ISSUE THREAD

**Issue by aeldidi** [CMPUT301W23T12/6ixStacks#29]
As a player, I want to be able to spend my points on new QR codes.

# Acceptance Criteria 
- A shop page allows players to buy QR codes of a certain rarity
- Points gained from QR codes can be spent in a shop

# Unknown 
- How much should things cost
- What exactly should there be available to spend on

**Comment by AdibNasreddine** [comment]
Blocked by #5

**Comment by aeldidi** [comment]
note that right now you can click the buttons and it will add the QR code to your account, but it won't subtract from your actual points.
