### ISSUE TITLE
Storyboarding

### ISSUE THREAD

**Issue by aeldidi** [CMPUT301W23T12/6ixStacks#3]
Form the initial partial user stories into a backlog of the product's requirements. For each user story, estimate its size in story points, and denote its risk level (i.e., low, medium, or high). These requirements will likely evolve and should be maintained up-to-date throughout the project.

**Comment by MohamedAl-Nassirat** [comment]
Done. https://github.com/CMPUT301W23T12/6ixStacks/wiki/UI-Mockups-and-Storyboard-Sequences:
