### ISSUE TITLE
Ability to add friends

### ISSUE THREAD

**Issue by aeldidi** [CMPUT301W23T12/6ixStacks#31]
As a player, I want to add friends so I can see their profile easily.

# Acceptance Criteria 
- The social tab has a "Add a Friend" button which allows searching for people to add
- Adding a friend should add them to a friend list on the social tab
- The leaderboard will display a friends only leaderboard, which is ranked separately from the global leaderboard

# Unknown 
- Is there a limit on the number of friends?

**Comment by MohamedAl-Nassirat** [comment]
#16 completed, no longer blocked

**Comment by aeldidi** [comment]
Closed because we decided not to
