### ISSUE TITLE
View friends on map

### ISSUE THREAD

**Issue by aeldidi** [CMPUT301W23T12/6ixStacks#32]
As a player, I want to see my friends on the map if they are nearby and currently playing.

# Acceptance Criteria 
- On the map, any nearby online players should appear
- Clicking them takes you to the profile page

# Unknown 
- How do we keep a live updating location for each player?

**Comment by AdibNasreddine** [comment]
Blocked by #6

**Comment by aeldidi** [comment]
closed because we decided not to
