### ISSUE TITLE
Firebase Integration + Wrapper

### ISSUE THREAD

**Issue by MohamedAl-Nassirat** [CMPUT301W23T12/6ixStacks#37]
Firebase Initial Integration

Documentation for using Wrapper will be provided here upon competition

**Comment by MohamedAl-Nassirat** [comment]
Firebase integration is now setup and working with Analytics for future use.
Firebase Wrapper is working in an early prototype stage where we have 3 methods `createCollection`, `addData`, `readData` so that any class within the App strutcture can call these methods to access the Firebase database.

Still needs some tuning and error handling, so don't use just yet. Will update as soon as it gets polished and will be moved to Staging for pulling.

[Branch working on Wrapper](/CMPUT301W23T12/6ixStacks/tree/fbIntegration)

**Comment by aeldidi** [comment]
Some ideas for the Firebase Wrapper API:

```java

FBDocument d = new FBDocument("name", "id");
d.put("key", 76)
d.update("key", "value")
d.remove("key")
d.getAsync("key", () -> {
});

```

**Comment by MohamedAl-Nassirat** [comment]
## FirebaseWrapper API Documentation

The FirebaseWrapper is a collection of static methods for interacting with Firebase Firestore. Here's an overview of the available methods:

##  addData
```java
public static void addData(String collectionName, String documentID, Map<String, Object> data)
```
Adds a new document to the specified collection with the given documentID and data. If the document already exists, the data will be overwritten.

Parameters:
-   `collectionName` - the name of the collection to add the document to. If the collection name doesn't exist, it will create a new one with the given name for you.
-    `documentID` - the ID to use for the new document.  If the document name doesn't exist, it will create a new one with the given name for you.
-  `data` - a hashmap of data to add to the document.

### Example usage:
```java
Map<String, Object> data = new HashMap<>();
data.put("name", "John Doe");
data.put("age", 42);
FirebaseWrapper.addData("users", "user123", data);
```
Firebase Database Preview:

![image](https://user-images.githubusercontent.com/96555957/220222476-06e7aa91-0bfc-4d56-bd4a-1d411d6bff22.png)


##  updateData
```java
public static void updateData(String collectionName, String documentID, Map<String, Object> data)
```
Updates the specified document in the specified collection with the given data.

Parameters:
-   `collectionName` - the name of the collection containing the document to update.
-    `documentID` - the ID of the document to update.
-  `data` - a hashmap of data to update in the document.

### Example usage:
```java
// This will delete the field "age" from the database
Map<String, Object> updateData = new HashMap<>();
updateData.put("age", FieldValue.delete());
FirebaseWrapper.updateData("users", "users123", updateData);

// This will update the field "name" in the database
updateData.put("name", "Not John Doe");
FirebaseWrapper.updateData("users", "users123", updateData);
```
Firebase Database Preview:
![image](https://user-images.githubusercontent.com/96555957/220223306-92d6c0c0-1878-45bf-a464-34078e8e6383.png)

## readData
```java
public static void readData(String collectionName, String documentID)
```
Reads the specified document from the specified collection and logs its data to the console.

Parameters:
- `collectionName` - the name of the collection containing the document to read.
- `documentID` - the ID of the document to read.

### Example usage:
```java
FirebaseWrapper.readData("users", "user123");
```
![image](https://user-images.githubusercontent.com/96555957/220223768-4f0089e5-e312-4d3e-a700-e6220460bac5.png)


## deleteDocument
```java
public static void deleteDocument(String collectionName, String documentName)
```
Deletes the specified document from the specified collection.
Parameters:
- `collectionName` - the name of the collection containing the document to read.
- `documentID` - the ID of the document to read.
### Example usage:
```java
FirebaseWrapper.deleteDocument("users", "user123");
```

Firebase Database Preview:
![image](https://user-images.githubusercontent.com/96555957/220223925-11ab70f8-7a4a-4ff6-b3ff-e87dd28a0544.png)
