### ISSUE TITLE
Spam add QR codes lags FireBase

### ISSUE THREAD

**Issue by MohamedAl-Nassirat** [CMPUT301W23T12/6ixStacks#88]
When you spam add QR codes to your account from the shop, Firebase will not be able to keep up and eventually just freeze at the last known qr code, so if you user spams 13 qr code purchases at the shop, it will stop at 8 and not fetch the 5 other ones they purchased. We can add a cooldown time before buying new QR codes

**Comment by MohamedAl-Nassirat** [comment]
This is the same idea for deleting a QR code, spam delete or add will cause firebase to lag and not be able to handle the process. We can add a cooldown to this as well

**Comment by aeldidi** [comment]
We plan to add some kind of animation after buying QR codes, so later this won't be an issue. Its also helpful during development to be able to quickly add a couple QR codes without having to wait for an animation to finish.
